name: build_distribution_app
description: "BDA — удобный инструмент для разработчиков, который упрощает распространение Android-сборок (.apk и .aab) среди команды, тестировщиков и клиентов."
publish_to: 'https://github.com/nvsces/build_distribution_app' 


version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  open_file: ^3.5.10
  android_intent_plus: ^5.3.0
  googleapis: ^13.1.0
  googleapis_auth: ^1.4.0
  http: ^0.13.6
  installed_apps: ^1.6.0
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  shared_preferences: ^2.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/config.json
    - assets/logo.png
    - assets/log_f.png
    - assets/ic_launcher.png

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/log_f.png"
  min_sdk_android: 21